import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("SaS - HW2")
        MainWindow.resize(1109, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 200, 1081, 771))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 331, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_faz2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_faz2.setObjectName("lineEdit_faz2")
        self.gridLayout.addWidget(self.lineEdit_faz2, 2, 2, 1, 1)
        self.lineEdit_genlik2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_genlik2.setObjectName("lineEdit_genlik2")
        self.gridLayout.addWidget(self.lineEdit_genlik2, 2, 0, 1, 1)
        self.lineEdit_frekans3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_frekans3.setObjectName("lineEdit_frekans3")
        self.gridLayout.addWidget(self.lineEdit_frekans3, 3, 1, 1, 1)
        self.lineEdit_genlik3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_genlik3.setObjectName("lineEdit_genlik3")
        self.gridLayout.addWidget(self.lineEdit_genlik3, 3, 0, 1, 1)
        self.lineEdit_faz3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_faz3.setObjectName("lineEdit_faz3")
        self.gridLayout.addWidget(self.lineEdit_faz3, 3, 2, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 1, 3, 1, 1)
        self.lineEdit_frekans2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_frekans2.setObjectName("lineEdit_frekans2")
        self.gridLayout.addWidget(self.lineEdit_frekans2, 2, 1, 1, 1)
        self.lineEdit_faz1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_faz1.setObjectName("lineEdit_faz1")
        self.gridLayout.addWidget(self.lineEdit_faz1, 1, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 3, 1, 1)
        self.lineEdit_genlik1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_genlik1.setObjectName("lineEdit_genlik1")
        self.gridLayout.addWidget(self.lineEdit_genlik1, 1, 0, 1, 1)
        self.lineEdit_frekans1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_frekans1.setObjectName("lineEdit_frekans1")
        self.gridLayout.addWidget(self.lineEdit_frekans1, 1, 1, 1, 1)
        self.label_genlik = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_genlik.setFont(font)
        self.label_genlik.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_genlik.setObjectName("label_genlik")
        self.gridLayout.addWidget(self.label_genlik, 0, 0, 1, 1)
        self.label_frekans = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_frekans.setFont(font)
        self.label_frekans.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_frekans.setObjectName("label_frekans")
        self.gridLayout.addWidget(self.label_frekans, 0, 1, 1, 1)
        self.label_faz = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_faz.setFont(font)
        self.label_faz.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_faz.setObjectName("label_faz")
        self.gridLayout.addWidget(self.label_faz, 0, 2, 1, 1)
        self.pushButton_plot1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot1.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.pushButton_plot1.setObjectName("pushButton_plot1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 170, 431, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(600, 10, 241, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_b2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_b2.setObjectName("lineEdit_b2")
        self.gridLayout_2.addWidget(self.lineEdit_b2, 2, 2, 1, 1)
        self.lineEdit_a5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_a5.setObjectName("lineEdit_a5")
        self.gridLayout_2.addWidget(self.lineEdit_a5, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_a3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_a3.setObjectName("lineEdit_a3")
        self.gridLayout_2.addWidget(self.lineEdit_a3, 3, 1, 1, 1)
        self.lineEdit_b1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_b1.setObjectName("lineEdit_b1")
        self.gridLayout_2.addWidget(self.lineEdit_b1, 1, 2, 1, 1)
        self.lineEdit_a2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_a2.setObjectName("lineEdit_a2")
        self.gridLayout_2.addWidget(self.lineEdit_a2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_b4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_b4.setObjectName("lineEdit_b4")
        self.gridLayout_2.addWidget(self.lineEdit_b4, 4, 2, 1, 1)
        self.lineEdit_a4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_a4.setObjectName("lineEdit_a4")
        self.gridLayout_2.addWidget(self.lineEdit_a4, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_a1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_a1.setObjectName("lineEdit_a1")
        self.gridLayout_2.addWidget(self.lineEdit_a1, 1, 1, 1, 1)
        self.lineEdit_b3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_b3.setObjectName("lineEdit_b3")
        self.gridLayout_2.addWidget(self.lineEdit_b3, 3, 2, 1, 1)
        self.lineEdit_b5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_b5.setObjectName("lineEdit_b5")
        self.gridLayout_2.addWidget(self.lineEdit_b5, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.pushButton_plot2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot2.setGeometry(QtCore.QRect(700, 170, 75, 23))
        self.pushButton_plot2.setObjectName("pushButton_plot2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(890, 40, 121, 81))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_T = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.gridLayout_3.addWidget(self.lineEdit_T, 1, 1, 1, 1)
        self.lineEdit_a0 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_a0.setObjectName("lineEdit_a0")
        self.gridLayout_3.addWidget(self.lineEdit_a0, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.plot_layout = QtWidgets.QVBoxLayout(self.widget)
        self.plot_layout.addWidget(self.canvas)        
        
        self.pushButton_plot1.clicked.connect(self.plot1)
        self.pushButton_plot2.clicked.connect(self.plot2)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def plot2(self):
        self.label.setText("")
        if(self.lineEdit_a0.text() == "" or
           self.lineEdit_a1.text() == "" or
           self.lineEdit_a2.text() == "" or
           self.lineEdit_a3.text() == "" or
           self.lineEdit_a4.text() == "" or
           self.lineEdit_a5.text() == "" or
           self.lineEdit_b1.text() == "" or
           self.lineEdit_b2.text() == "" or
           self.lineEdit_b3.text() == "" or
           self.lineEdit_b4.text() == "" or
           self.lineEdit_b5.text() == "" or
           self.lineEdit_T.text() == "" ):
            self.label.setText("Lütfen tüm alanları doldurunuz!")
            return
        elif(float(self.lineEdit_T.text()) <= 0):
            self.label.setText("Periyot pozitif bir değer olmalıdır!")
            return
        
        a = [float(self.lineEdit_a1.text()), float(self.lineEdit_a2.text()), float(self.lineEdit_a3.text()), float(self.lineEdit_a4.text()), float(self.lineEdit_a5.text())]
        b = [float(self.lineEdit_b1.text()), float(self.lineEdit_b2.text()), float(self.lineEdit_b3.text()), float(self.lineEdit_b4.text()), float(self.lineEdit_b5.text())]
        
        y = float(self.lineEdit_a0.text())
        T = float(self.lineEdit_T.text())
        w = float(2 * np.pi / T)
        k = int(self.comboBox.currentText())
        t = np.linspace(-1*T, T, 1000)
        
        for i in range(k):
            y += (a[i] * np.cos((i+1) * w * t) + b[i] * np.sin((i+1) * w * t))
        
        self.figure.clear()
        
        ax = self.figure.add_subplot(111)
        ax.plot(t, y, label='Sentez sinyal')
        ax.set_title('Sentez sinyal')
        ax.set_xlabel("t")

        self.figure.tight_layout()
        self.canvas.draw()
    
    def plot1(self):
        self.label.setText("")
        
        if(self.lineEdit_genlik1.text() == "" or 
           self.lineEdit_genlik2.text() == "" or
           self.lineEdit_genlik3.text() == "" or
           self.lineEdit_frekans1.text() == "" or
           self.lineEdit_frekans2.text() == "" or
           self.lineEdit_frekans3.text() == "" or
           self.lineEdit_faz1.text() == "" or
           self.lineEdit_faz2.text() == "" or
           self.lineEdit_faz3.text() == "" ):
            self.label.setText("Lütfen tüm alanları doldurunuz!")
            return
        elif (float(self.lineEdit_frekans1.text()) <= 0 or
              float(self.lineEdit_frekans2.text()) <= 0 or
              float(self.lineEdit_frekans3.text()) <= 0):
            self.label.setText("Frekans değerleri pozitif olmalıdır!")
            return 
        
        x1 = 0
        x2 = 0
        x3 = 0
        
        periyot1 = 1 / float(self.lineEdit_frekans1.text())
        periyot2 = 1 / float(self.lineEdit_frekans2.text())
        periyot3 = 1 / float(self.lineEdit_frekans3.text())
        periyot = float(max(periyot1, periyot2, periyot3))
        t = np.linspace(-1*periyot, periyot, 1000)
        
        genlik = float(self.lineEdit_genlik1.text())
        frekans = float(self.lineEdit_frekans1.text())
        faz = float(self.lineEdit_faz1.text())
        if(self.comboBox_1.currentText() == "cos"):
            x1 = genlik * np.cos(2 * np.pi * frekans * t + np.pi * faz)
        else:
            x1 = genlik * np.sin(2 * np.pi * frekans * t + np.pi * faz)
            
        genlik = float(self.lineEdit_genlik2.text())
        frekans = float(self.lineEdit_frekans2.text())
        faz = float(self.lineEdit_faz2.text())
        if(self.comboBox_2.currentText() == "cos"):
            x2 = genlik * np.cos(2 * np.pi * frekans * t + np.pi * faz)
        else:
            x2 = genlik * np.sin(2 * np.pi * frekans * t + np.pi * faz)
            
        genlik = float(self.lineEdit_genlik3.text())
        frekans = float(self.lineEdit_frekans3.text())
        faz = float(self.lineEdit_faz3.text())
        if(self.comboBox_3.currentText() == "cos"):
            x3 = genlik * np.cos(2 * np.pi * frekans * t + np.pi * faz)
        else:
            x3 = genlik * np.sin(2 * np.pi * frekans * t + np.pi * faz)
        
        xToplam = x1 + x2 + x3
        
        self.figure.clear()
        
        ax1 = self.figure.add_subplot(411)
        ax2 = self.figure.add_subplot(412)
        ax3 = self.figure.add_subplot(413)
        ax4 = self.figure.add_subplot(414)

        ax1.plot(t, x1, label='1. Sinyal')
        ax1.set_title('1. Sinyal')
        ax2.plot(t, x2, label='2. Sinyal')
        ax2.set_title('2. Sinyal')
        ax3.plot(t, x3, label='3. Sinyal')
        ax3.set_title('3. Sinyal')
        ax4.plot(t, xToplam, label='Sentez Sinyal', color="r")
        ax4.set_title('Sentez sinyal')
        ax4.set_xlabel("t")

        self.figure.tight_layout()
        self.canvas.draw()
    
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("SaS - HW2", "SaS - HW2"))
        self.comboBox_1.setItemText(0, _translate("SaS - HW2", "cos"))
        self.comboBox_1.setItemText(1, _translate("SaS - HW2", "sin"))
        self.comboBox_2.setItemText(0, _translate("SaS - HW2", "cos"))
        self.comboBox_2.setItemText(1, _translate("SaS - HW2", "sin"))
        self.comboBox_3.setItemText(0, _translate("SaS - HW2", "cos"))
        self.comboBox_3.setItemText(1, _translate("SaS - HW2", "sin"))
        self.label_genlik.setText(_translate("SaS - HW2", "Genlik"))
        self.label_frekans.setText(_translate("SaS - HW2", "Frekans"))
        self.label_faz.setText(_translate("SaS - HW2", "Faz"))
        self.pushButton_plot1.setText(_translate("SaS - HW2", "Çiz"))
        self.label_5.setText(_translate("SaS - HW2", "k=4"))
        self.label_4.setText(_translate("SaS - HW2", "k=3"))
        self.label_6.setText(_translate("SaS - HW2", "k=5"))
        self.label_2.setText(_translate("SaS - HW2", "k=1"))
        self.label_3.setText(_translate("SaS - HW2", "k=2"))
        self.label_7.setText(_translate("SaS - HW2", "Ak"))
        self.label_8.setText(_translate("SaS - HW2", "Bk"))
        self.pushButton_plot2.setText(_translate("SaS - HW2", "Çiz"))
        self.label_10.setText(_translate("SaS - HW2", "T0"))
        self.label_9.setText(_translate("SaS - HW2", "A0"))
        self.comboBox.setItemText(0, _translate("SaS - HW2", "1"))
        self.comboBox.setItemText(1, _translate("SaS - HW2", "2"))
        self.comboBox.setItemText(2, _translate("SaS - HW2", "3"))
        self.comboBox.setItemText(3, _translate("SaS - HW2", "4"))
        self.comboBox.setItemText(4, _translate("SaS - HW2", "5"))
        self.comboBox.setCurrentIndex(4)
        self.label_11.setText(_translate("SaS - HW2", "k"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())